// const { mainCompareTheTriplets } = require('./challenges/compare-the-triplets');
// const { mainAVeryBigSum } = require('./challenges/a-very-big-sum');
// const { mainDiagonalDifference } = require('./challenges/diagonal-difference');
// const { mainPlusMinus } = require('./challenges/plus-minus');
// const { mainStaircase } = require('./challenges/staircase');
// const { mainMiniMaxSum } = require('./challenges/min-max-sum');
// const { mainBirthdayCakeCandles } = require('./challenges/birthday-cake-candles');
// const { mainTimeConversion } = require('./challenges/time-conversion');
// const { mainGradingStudents } = require('./challenges/grading-students');
// const { mainCountApplesAndOranges } = require('./challenges/apple-and-orange');
// const { mainNumberLineJumps } = require('./challenges/number-line-jumps');
// const { mainBetweenTwoSets } = require('./challenges/between-two-sets');
// const { mainSimpleArraySum } = require('./challenges/simple-array-sum');
// const { mainPlayWithWords } = require('./challenges/play-with-words');
// const { mainBreakingRecords } = require('./challenges/breaking-the-records');
// const { mainBirthday } = require('./challenges/birthday');
// const { mainDivisibleSumPairs } = require('./challenges/divisible-sum-pairs');
// const { mainMigratoryBirds } = require('./challenges/migratory-birds');
// const { mainDayOfProgrammer } = require('./challenges/day-of-the-programmer');
// const { mainBillDivision } = require('./challenges/bill-divsion');
// const { mainSalesByMatch } = require('./challenges/sales-by-match');
// const { mainDrawingBook } = require('./challenges/drawing-book');
// const { mainCountingValleys } = require('./challenges/counting-valleys');
// const { mainElectronicsShop } = require('./challenges/electronics-shop');
// const { mainCatAndMouse } = require('./challenges/cats-and-a-mouse');
// const { mainFormingMagicSquare } = require('./challenges/forming-a-magic-square');
const { mainPickingNumbers } = require('./challenges/picking-numbers');

// mainCompareTheTriplets();
// mainAVeryBigSum();
// mainDiagonalDifference();
// mainPlusMinus();
// mainStaircase();
// mainMiniMaxSum();
// mainBirthdayCakeCandles();
// mainTimeConversion();
// mainGradingStudents();
// mainCountApplesAndOranges();
// mainNumberLineJumps();
// mainBetweenTwoSets();
// mainSimpleArraySum();
// mainPlayWithWords();
// mainBreakingRecords();
// mainBirthday();
// mainDivisibleSumPairs();
// mainMigratoryBirds();
// mainDayOfProgrammer();
// mainBillDivision();
// mainDrawingBook();
// mainCountingValleys();
// mainElectronicsShop();
// mainCatAndMouse();
// mainFormingMagicSquare();
mainPickingNumbers();
