// const { mainCompareTheTriplets } = require('./challenges/compare-the-triplets');
// const { mainAVeryBigSum } = require('./challenges/a-very-big-sum');
// const { mainDiagonalDifference } = require('./challenges/diagonal-difference');
// const { mainPlusMinus } = require('./challenges/plus-minus');
// const { mainStaircase } = require('./challenges/staircase');
// const { mainMiniMaxSum } = require('./challenges/min-max-sum');
// const { mainBirthdayCakeCandles } = require('./challenges/birthday-cake-candles');
// const { mainTimeConversion } = require('./challenges/time-conversion');
// const { mainGradingStudents } = require('./challenges/grading-students');
// const { mainCountApplesAndOranges } = require('./challenges/apple-and-orange');
// const { mainNumberLineJumps } = require('./challenges/number-line-jumps');
const { mainBetweenTwoSets } = require('./challenges/between-two-sets');

// mainCompareTheTriplets();
// mainAVeryBigSum();
// mainDiagonalDifference();
// mainPlusMinus();
// mainStaircase();
// mainMiniMaxSum();
// mainBirthdayCakeCandles();
// mainTimeConversion();
// mainGradingStudents();
// mainCountApplesAndOranges();
// mainNumberLineJumps();
mainBetweenTwoSets();
